# Generated by Django 4.1.5 on 2023-01-22 12:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("time_allot", models.IntegerField()),
                ("tags", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("title", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField()),
                ("bio", models.TextField(blank=True)),
                ("phone_num", models.TextField(blank=True, max_length=15)),
                ("name", models.TextField(blank=True, max_length=100)),
                ("dob", models.TextField(blank=True, max_length=20)),
                ("gender", models.TextField(blank=True, max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
