# Generated by Django 4.1.5 on 2023-01-30 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "instructor",
            "0003_alter_livetime_close_time_alter_livetime_start_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="quizpost",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
