# Generated by Django 4.1.5 on 2023-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="rating",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="quizrecord",
            name="correct",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="quizrecord",
            name="incorrect",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="quizrecord",
            name="rating_diff",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="quizrecord",
            name="time_taken",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="quizrecord",
            name="total",
            field=models.IntegerField(default=None),
        ),
    ]
